# Adapted from stage1/docker-php

language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - sudo sh -c "wget -qO- https://get.docker.io/gpg | apt-key add -"
  - sudo sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
  - sudo apt-get update
  - echo exit 101 | sudo tee /usr/sbin/policy-rc.d
  - sudo chmod +x /usr/sbin/policy-rc.d
  - sudo apt-get install -qy slirp lxc lxc-docker
  - git clone git://github.com/jpetazzo/sekexe
  - composer install --dev

script:
  - sekexe/run "`pwd`/.travis.sh"

env:
  global:
  - secure: FMDbDiXaSfyaVMtuHsWmtRS6HZPBtTWD+kIIKtdkzCqJewAGGn0GhOayPKuEyi9I6BCk1GIWLnrpLmPno9QbpV8bZxRY0xQXRPslCQV1DxWgRBamVckA8EOfjE7irDwrzAoymhJJrlrCz0zCFt7k0G6EuESk+jJN9FsclfXbqZU=

# http://stackoverflow.com/questions/18027115/committing-via-travis-ci-failing
after_success:
  - composer install --no-dev
  - git checkout -b master-deps
  - git add -f vendor/
  - git commit -m "Travis built dependencies."
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git push -f origin master-deps
