#!/bin/bash
docker ps -a | grep -q source-broadcast-proxy && docker start -ai source-broadcast-proxy || \
docker run -it \
  --net=host \
  --name source-broadcast-proxy \
  boombatower/source-broadcast-proxy
